blank_issues_enabled: false
contact_links:
  - name: Dudas o Preguntas
    url: https://github.com/cl2raul66/MauiPdfGenerator/discussions
    about: Por favor usa las Discusiones para preguntas, no los Issues.
